global:
  resolve_timeout: 2m

route:
  receiver: 'send_to_dingtalk_ops'
  group_by: ['opsgroup']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 4h
  routes:
  - receiver: 'send_to_dingtalk_loan'
    group_by: ['loangroup']
    match:
      team: loan
  - receiver: 'send_to_dingtalk_wms'
    group_by: ['wmsgroup']
    match:
      team: wms
  - receiver: 'send_to_dingtalk_tms'
    group_by: ['tmsgroup']
    match:
      team: tms
  - receiver: 'send_to_dingtalk_sell'
    group_by: ['sellgroup']
    match:
      team: sell
  - receiver: 'send_to_dingtalk_frame'
    group_by: ['framegroup']
    match:
      team: frame
  - receiver: 'send_to_dingtalk_cloan'
    group_by: ['cloangroup']
    match:
      team: cloan
  - receiver: 'send_to_dingtalk_pay'
    group_by: ['paygroup']
    match:
      team: pay

receivers:
- name: 'send_to_dingtalk_ops'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhookops/send'
- name: 'send_to_dingtalk_loan'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhookloan/send'
- name: 'send_to_dingtalk_wms'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhookwms/send'
- name: 'send_to_dingtalk_tms'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhooktms/send'
- name: 'send_to_dingtalk_sell'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhooksell/send'
- name: 'send_to_dingtalk_frame'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhookframe/send'
- name: 'send_to_dingtalk_cloan'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhookcloan/send'
- name: 'send_to_dingtalk_pay'
  webhook_configs:
  - send_resolved: false
    url: 'http://localhost:8060/dingtalk/webhookpay/send'

inhibit_rules:
  - source_match:
      server_status: ss
    target_match_re:
      team: '^[a-z]+$'
    equal: ['job', 'instance']
